### ISSUE TITLE
Open ne prikazuje kompletan sadrzaj foldera

### ISSUE THREAD

**Issue by spaske00** [MATF-RS20/RS024-sourceexplorer#15]
Klik na open kada se pokrene aplikacija ne prikazuje celokupan sadrzaj foldera

**Comment by djordjetane** [comment]
Ne prikazuje jer filtrira po ekstenziji .cpp, .hpp, .h ; dodaj u editor_util.cpp eksenzije koje smatras da treba, ili ih meni napisi ovde.
Jer koja je poenta da imamo fajlove koji ne mogu da se analiziraju (tipa .txt ,. py i sl)

**Comment by spaske00** [comment]
Ja nemam oci...
