### ISSUE TITLE
Srediti nazive cvorova i izbaciti cvorove duplikate

### ISSUE THREAD

**Issue by Robotmurlock** [MATF-RS20/RS024-sourceexplorer#5]
Duplikati(?): Base::D(), Derived::D(), D()
Vecina cvorova u grafu se ne prikazuje iz ovog razloga.

19
sup
main
        base::base()
        base::D(int, double)
        derived::derived()
        derived::D(int, double)
        operator new(unsigned long)
        derived::derived()
        derived::~derived()
        base::~base()
        derived::~derived()
        base::~base()
--Nema prethodnika
B()
        C(char)
C(int)
llvm.dbg.declare
--Nema prethodnika
D(double, double)
        A()
        B()
        C(int)
        G()
--Nema prethodnika
G()
        C(int)
        B()
--Nema prethodnika
A()
        B()
        C(char)
__gxx_personality_v0
base::base()
base::D(int, double)
derived::derived()
        base::base()
derived::D(int, double)
operator new(unsigned long)
derived::~derived()
        base::~base()
base::~base()
derived::~derived()
        derived::~derived()
        operator delete(void*)
operator delete(void*)
base::~base()
        base::~base()
        operator delete(void*)
-- Nema prethodnika
C(char)

**Comment by spaske00** [comment]
class base
{
public:
  virtual void D(int, double){}
  virtual ~base() {}
};

class derived : public base
{
public:
  virtual void D(int, double) override {}
};

int main()
{
  base b;
  b.D(3, 3.4);

  derived d;
  d.D(3,3.4);

  base *bs = new derived;
  bs->D(5, 5.4);

  delete bs;
  return 0;
}

Ovo je fajl koji generise takav callgraph. Nema duplikata.

**Comment by spaske00** [comment]
Da ubacimo opciju da izbaci konstruktore i destruktore?

**Comment by Robotmurlock** [comment]
Sta je onda D()?
